CC=gcc
LD=ld
ASM=nasm

CFLAGS=-ffreestanding -m32 -c -fno-stack-protector -fno-builtin -fno-pic -fno-pie -I.
LDFLAGS=-m elf_i386 -T linker/linker.ld -nostdlib

KERNEL_OBJ = kernel/kernel.o kernel/game.o kernel/ata.o kernel/ahci.o kernel/store.o kernel/idt.o kernel/elf.o kernel/exec.o kernel/linux.o arch/x86/linux_asm.o

# ELF32 command binaries.  Every source in bin/ is compiled with
# plain host gcc (-m32, freestanding, ET_REL) into its own standalone
# ELF32 binary in home/bin/, then embedded in the kernel image (via
# home.tar) as /bin/<name>.o, where the shell finds it at boot.
# tools/tcc/build-tcc.sh builds the TinyCC compiler the same way:
# home/bin/tcc.o -> /bin/tcc.o, so `tcc` is just another command.
# The only toolchain the build needs is gcc, nasm and ld.
BIN_SRC = $(wildcard bin/*.c)
BIN_OUT = $(BIN_SRC:bin/%.c=home/bin/%.o)
TCC_HDRS = $(wildcard tools/tcc/std-include/*.h tools/tcc/std-include/sys/*.h)
TCC_BUILD_SCRIPT ?= build-tcc.sh
TCC_SRC = tools/tcc/build-tcc.sh tools/tcc/build-tcc-arm64.sh tools/tcc/tanja-libc.c tools/tcc/tanja-libc.h \
          tools/tcc/tanja-tcc-main.c tools/tcc/install-headers.sh $(TCC_HDRS) \
          $(wildcard tools/tcc/tinycc/*.c) $(wildcard tools/tcc/tinycc/*.h) \
          $(wildcard tools/tcc/tanja-libc-include/*.h)
HOME_OBJ = home_tar.o


all: arch/x86/boot/tanja-base

BUILD_TS := $(shell date +%s)

include/build_id.h: $(wildcard kernel/*.c) $(wildcard fs/*.c) $(BIN_SRC) $(wildcard include/*.h) home.tar
	@echo "[GEN] include/build_id.h (build $(BUILD_TS))"
	@echo "/* Auto-generated by the build - do not edit or commit. */" > $@
	@echo "#define TANJA_BUILD_ID_LO $(BUILD_TS)u" >> $@
	@echo "#define TANJA_BUILD_ID_HI 0u" >> $@

.PHONY: home_image
home_image: home_tar.o

home/bin:
	mkdir -p home/bin

BIN_CFLAGS = -m32 -ffreestanding -fno-stack-protector -fno-builtin \
             -fno-pic -fno-pie -fno-common \
             -fno-asynchronous-unwind-tables \
             -Wno-builtin-declaration-mismatch -I include -I .

home/bin/%.o: bin/%.c include/tanja.h include/fs.h include/utf8.h | home/bin
	@echo "[CC] bin/$*.c (ELF32)"
	$(CC) $(BIN_CFLAGS) -c $< -o $@

# TinyCC builds with its own script (it needs per-file -D flags);
# install-headers.sh refreshes home/include/ from the header sets.
tools/tcc/tcc.o: $(TCC_SRC)
	@echo "[TCC] building TinyCC (freestanding i386 object)"
	(cd tools/tcc && ./$(TCC_BUILD_SCRIPT))
	(cd tools/tcc && ./install-headers.sh)

home/bin/tcc.o: tools/tcc/tcc.o | home/bin
	cp $< $@

home.tar: $(shell find home -type f -o -type d 2>/dev/null | grep -v '^home/bin/') $(BIN_OUT) home/bin/tcc.o
	@echo "[TAR] Packing home/ (binaries as /bin, headers as /include)"
	rm -rf .home-stage
	tar --format=ustar -cf $@ -C home .

home_tar.o: home.tar
	@echo "[OBJ] Embedding home/"
	$(LD) -r -b binary -m elf_i386 -o $@ $<

kernel/%.o: kernel/%.c
	@echo "[CC] kernel/$(notdir $<)"
	$(CC) $(CFLAGS) -o $@ $<


kernel/store.o: kernel/store.c include/build_id.h
	@echo "[CC] kernel/store.c"
	$(CC) $(CFLAGS) -o kernel/store.o kernel/store.c


arch/x86/idt_asm.o: arch/x86/idt_asm.asm
	@echo "[ASM] idt_asm.asm"
	$(ASM) -f elf32 arch/x86/idt_asm.asm -o arch/x86/idt_asm.o


fs/fs.o: fs/fs.c
	@echo "[CC] fs/fs.c"
	$(CC) $(CFLAGS) -o fs/fs.o fs/fs.c


arch/x86/boot/boot.o: arch/x86/boot/boot.asm | arch/x86/boot
	@echo "[ASM] boot.asm"
	$(ASM) -f elf32 arch/x86/boot/boot.asm -o arch/x86/boot/boot.o


arch/x86/linux_asm.o: arch/x86/linux_asm.asm
	@echo "[ASM] linux_asm.asm"
	$(ASM) -f elf32 arch/x86/linux_asm.asm -o arch/x86/linux_asm.o


arch/x86/boot/tanja-base: arch/x86/boot/boot.o arch/x86/idt_asm.o $(KERNEL_OBJ) fs/fs.o $(HOME_OBJ) | arch/x86/boot
	@echo "[LD] Linking..."
	$(LD) $(LDFLAGS) -o arch/x86/boot/tanja-base \
		arch/x86/boot/boot.o \
		arch/x86/idt_asm.o \
		$(KERNEL_OBJ) \
		fs/fs.o \
		$(HOME_OBJ)

	@echo
	@echo "[INFO] Kernel image ready at arch/x86/boot/tanja-base"
	@echo "[INFO] Command sources in bin/, built to home/bin/*.o -> /bin/<name>.o at boot"
	@echo "[INFO] Build tcc with: (cd tools/tcc && ./$(TCC_BUILD_SCRIPT))"
	@echo

clean:
	rm -f kernel/*.o fs/*.o
	rm -f arch/x86/boot/*.o arch/x86/boot/tanja-base
	rm -f arch/x86/*.o home.tar home_tar.o *.o
	rm -rf home/bin .home-stage include/build_id.h

.PHONY: all clean home_image
